### ISSUE TITLE
NG FOUND DURING ASSEMBLY LINE RUNNING IN SAMSUNG OK

### ISSUE THREAD

**Issue by Shivpal1996** [openai/baselines#1233]
Model A556 in this we found a issue of connector pressing damage.
 A156 BATTERY DENT
A042 LCD OUCH FAIL
A556 OCTA CCD FAIL
M346 DISPLAY LINING 
[Uploading Internal meeting W44.pptx…]()

```[tasklist]
### FILE 1
- [ ] OCTA + CU SHEET + BATTERY
- [ ] https://github.com/openai/baselines/issues/1204
- [ ] BATTERY DENT
- [ ] https://github.com/openai/baselines/issues/114
```

```[tasklist]
### CU OCTA + BATTERY
```

```[tasklist]
### Tasks
```
